name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  todolist-tests:
    runs-on: ubuntu-latest
    container: golang:1.23

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go test
        run: |
          go mod tidy
          go test -test.v ./...
